apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-db
  labels:
    db: acmeair-db
  namespace: acmeair
spec:
  replicas: 1
  selector:
    matchLabels:
      db: acmeair-db
  template:
    metadata:
      labels:
        db: acmeair-db
    spec:
      nodeSelector:
        node.openshift.io/os_id: rhcos
      containers:
      - image: quay.io/powercloud/acme-airlines-mac:mongodb-4.4.18-ml
        name: acmeair-db
        args: ["--dbpath","/data/db", "--auth"] #acmeair
        ports:
        - containerPort: 27017
          protocol: TCP
        env:
        - name: MONGO_INITDB_DATABASE
          value: acmeair
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: username
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: password
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
        - mountPath: /docker-entrypoint-initdb.d/
          name: mongodb-config
        securityContext:
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
        readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
      - name: mongodb-config
        secret:
          secretName: mongodb-config
          items:
          - key: acmeair.sh
            path: acmeair.sh
      restartPolicy: Always
