apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: acmeair 
namespace: acmeair

resources:
- ../../base
- pvc.yaml
- app.yaml
- db.yaml

sortOptions:
   order: fifo

images:
- name: quay.io/powercloud/acme-airlines-mac:acme-air-414
  newName: quay.io/powercloud/acme-airlines-mac  
  newTag: acme-air-414 
