apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-monolithic-java-deployment
  namespace: acmeair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acmeair
  template:
    metadata:
      labels:
        app: acmeair
        tier: monolithic
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        node.openshift.io/os_id: rhcos
      containers:
      - name: acmeair-java
        image: quay.io/powercloud/acme-airlines-mac:acme-air-414
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        - containerPort: 9443
        env:
        - name: MONGO_MANUAL
          value: "true"
        - name: MONGO_HOST
          value: "acmeair-db"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DBNAME
          value: "acmeair"
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: password
        resources:
          requests:
            cpu: "700m"